/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dhyppelypeli.dhyppelypeli;

import dhyppelypeli.Nappaimet.NappaintenVaihto;
import dhyppelypeli.PelinTiedot.PelinTiedot;


/**
 *
 * @author Tommi
 */
public class NappaintenVaihtoValikko extends javax.swing.JFrame {

    private PelinTiedot pelinTiedot;

    /**
     * Creates new form NewJFrame
     *
     * @param pelinTiedot sisältää pelin tiedot.
     */
    public NappaintenVaihtoValikko(PelinTiedot pelinTiedot) {
        this.setVisible(true);
        this.pelinTiedot = pelinTiedot;
        initComponents();
        nappaimet();
        nappainTekstit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oikeaPelaajaAlas = new javax.swing.JButton();
        oikeaPelaajaYlos = new javax.swing.JButton();
        vasenPelaajaYlos = new javax.swing.JButton();
        asetukset = new javax.swing.JButton();
        vasenPelaajaAlas = new javax.swing.JButton();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        teksti = new javax.swing.JTextField();
        label7 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        oikeaPelaajaAlas.setText("PelaajaYksiYlös");

        oikeaPelaajaYlos.setText("PelaajaKaksiYlös");

        vasenPelaajaYlos.setText("PelaajaYksiAlas");
        vasenPelaajaYlos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vasenPelaajaYlosActionPerformed(evt);
            }
        });

        asetukset.setText("Takaisin");
        asetukset.setToolTipText("");
        asetukset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asetuksetActionPerformed(evt);
            }
        });

        vasenPelaajaAlas.setText("PelaajaKaksiAlas");
        vasenPelaajaAlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vasenPelaajaAlasActionPerformed(evt);
            }
        });

        label2.setText("Ylä näppäin");

        label3.setText("Vasen näppäin");

        label5.setText("Oikea"
            + " näppäin");

        label6.setText("Ala"
            + " näppäin");

        teksti.setText("jTextField1");
        teksti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstiActionPerformed(evt);
            }
        });

        label7.setText("Vain Englannin kielen aakkoset käy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(vasenPelaajaAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(teksti, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(vasenPelaajaYlos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oikeaPelaajaAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(oikeaPelaajaYlos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(asetukset, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vasenPelaajaYlos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teksti, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oikeaPelaajaAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oikeaPelaajaYlos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vasenPelaajaAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(asetukset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekstiActionPerformed

    private void vasenPelaajaAlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vasenPelaajaAlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vasenPelaajaAlasActionPerformed

    private void asetuksetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asetuksetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asetuksetActionPerformed

    private void vasenPelaajaYlosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vasenPelaajaYlosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vasenPelaajaYlosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void nappaimet() {
        NappaintenVaihto kopioija = new NappaintenVaihto(teksti, this, pelinTiedot);
        asetukset.addActionListener(kopioija);
        oikeaPelaajaAlas.addActionListener(kopioija);
        oikeaPelaajaYlos.addActionListener(kopioija);
        vasenPelaajaYlos.addActionListener(kopioija);
        vasenPelaajaAlas.addActionListener(kopioija);
        teksti.addActionListener(kopioija);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asetukset;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private javax.swing.JButton oikeaPelaajaAlas;
    private javax.swing.JButton oikeaPelaajaYlos;
    private javax.swing.JTextField teksti;
    private javax.swing.JButton vasenPelaajaAlas;
    private javax.swing.JButton vasenPelaajaYlos;
    // End of variables declaration//GEN-END:variables

    private void nappainTekstit() {
        oikeaPelaajaAlas.setName("oikeaPelaajaAlas");
        oikeaPelaajaYlos.setName("oikeaPelaajaYlos");
        vasenPelaajaYlos.setName("vasenPelaajaYlos");
        vasenPelaajaAlas.setName("vasenPelaajaAlas");
        asetukset.setName("Takaisin");
        oikeaPelaajaAlas.setText((char) pelinTiedot.getPeliHahmo().getAlaNappain() + "");
        oikeaPelaajaYlos.setText((char) pelinTiedot.getPeliHahmo().getYlaNappain() + "");
        vasenPelaajaAlas.setText((char) pelinTiedot.getPeliHahmo().getAlaNappain() + "");
        vasenPelaajaYlos.setText((char) pelinTiedot.getPeliHahmo().getYlaNappain() + "");
        teksti.setText("");
    }
}
