package dhyppelypeli.dhyppelypeli;

import dhyppelypeli.Nappaimet.KlikkaustenKuuntelija;
import dhyppelypeli.PelinTiedot.PelinTiedot;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tommi
 */
public class Paavalikko extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     *
     * @param pelintiedot sisältää peliin kuuluvat tiedot
     */
    public Paavalikko(PelinTiedot pelintiedot) {
        this.setVisible(true);
        pelinTiedot = pelintiedot;
        initComponents();
        nappaimet();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelaa = new javax.swing.JButton();
        asetukset = new javax.swing.JButton();
        lopeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pelaa.setText("Pelaa");
        pelaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelaaActionPerformed(evt);
            }
        });

        asetukset.setText("Asetukset");

        lopeta.setText("Lopeta");
        lopeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(pelaa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(asetukset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lopeta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(pelaa)
                .addGap(29, 29, 29)
                .addComponent(asetukset)
                .addGap(27, 27, 27)
                .addComponent(lopeta)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lopetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lopetaActionPerformed

    private void pelaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelaaActionPerformed

    /**
     * @param args the command line arguments
     */
    private PelinTiedot pelinTiedot;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asetukset;
    private javax.swing.JButton lopeta;
    private javax.swing.JButton pelaa;
    // End of variables declaration//GEN-END:variables
/**
     * Metodi valmistaan nappaimien toiminnallisuuden.
     */
    public void nappaimet() {
        KlikkaustenKuuntelija kopioija = new KlikkaustenKuuntelija(this, pelinTiedot);
        pelaa.addActionListener(kopioija);
        asetukset.addActionListener(kopioija);
        lopeta.addActionListener(kopioija);
    }

}
